version: '3.9'
name: intershop

services:
  postgres:
    image: postgres:15
    container_name: intershop-postgres
    restart: always
    environment:
      POSTGRES_DB: intershop_db
      POSTGRES_USER: intershop_user
      POSTGRES_PASSWORD: intershop_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: intershop-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /data

  redis:
    image: redis:7.2-alpine
    container_name: intershop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: intershop
    container_name: intershop-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
