version: '3.9'
name: intershop

services:
  postgres:
    image: postgres:15
    container_name: intershop-postgres
    restart: always
    environment:
      POSTGRES_DB: intershop_db
      POSTGRES_USER: intershop_user
      POSTGRES_PASSWORD: intershop_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: intershop-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /data

  app:
    image: intershop
    container_name: intershop-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
