
version: '3.9'
name: intershop

services:
  postgres:
    image: postgres:15
    container_name: intershop-postgres
    restart: always
    environment:
      POSTGRES_DB: intershop_db
      POSTGRES_USER: intershop_user
      POSTGRES_PASSWORD: intershop_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: intershop-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /data

  redis:
    image: redis:7.2-alpine
    container_name: intershop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    volumes:
     - /opt/keycloak/data/import
    command: ["start-dev"]

  app:
    image: intershop
    container_name: intershop-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  payment:
    image: payment
    container_name: intershop-payment
    build:
      context: ./payment
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/intershop_db
      SPRING_LIQUIBASE_USER: intershop_user
      SPRING_LIQUIBASE_PASSWORD: intershop_password
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop_db
      SPRING_R2DBC_USERNAME: intershop_user
      SPRING_R2DBC_PASSWORD: intershop_password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/master
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

